const watchData = [
  {
    id: 1,
    img: "https://monochrome-watches.com/app/uploads/2020/08/Rolex-Submariner-16610-Black-1.jpg",
    brand: "Rolex",
    price: 8500,
    model: "Submariner",
    made: "Switzerland",
  },
  {
    id: 2,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDLKnZZeI9vW70TdIXQQ6jb8CR1HUMZR7yaBb1mEOlxA&s",
    brand: "Casio",
    price: 45,
    model: "G-Shock GA-2100",
    made: "Japan",
  },
  {
    id: 3,
    img: "https://img.chrono24.com/images/uhren/4aq2fyxk92na-upeom9am4p4wm076duk24b0r-ExtraLarge.jpg",
    brand: "Omega",
    price: 5200,
    model: "Seamaster",
    made: "Switzerland",
  },
  {
    id: 4,
    img: "https://img.chrono24.com/images/uhren/44561162-780dnmevwfl1nritrof4qscu-ExtraLarge.jpg",
    brand: "Seiko",
    price: 320,
    model: "5 Sports",
    made: "Japan",
  },
  { id: 5, brand: "Tissot", price: 450, model: "PRX", made: "Switzerland" },
  { id: 6, brand: "Citizen", price: 280, model: "Eco-Drive", made: "Japan" },
  { id: 7, brand: "Fossil", price: 110, model: "Gen 6", made: "USA" },
  {
    id: 8,
    brand: "Tag Heuer",
    price: 2100,
    model: "Carrera",
    made: "Switzerland",
  },
  {
    id: 9,
    brand: "Patek Philippe",
    price: 35000,
    model: "Nautilus",
    made: "Switzerland",
  },
  {
    id: 10,
    brand: "Swatch",
    price: 75,
    model: "Originals",
    made: "Switzerland",
  },
];
export { watchData };
